import { stringify } from "yaml"
import type { FeaturedArticle } from "./obsidianFeaturedContent"
import type { HomepageConfiguration } from "./obsidianHomepage"
import { slugTag } from "./path"

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
}

function displayDate(value: string): string {
  return value.replaceAll("-", ".")
}

function renderFeaturedCard(item: FeaturedArticle, indentation: string): string {
  const thumbnail = item.thumbnail
    ? `${indentation}  <a class="featured-card-media" href="${escapeHtml(item.href)}" tabindex="-1" aria-hidden="true">
${indentation}    <img src="${escapeHtml(item.thumbnail)}" alt="" loading="lazy">
${indentation}  </a>
`
    : ""
  const tags = item.tags
    .slice(0, 4)
    .map(
      (tag) =>
        `${indentation}        <a class="featured-card-tag" href="/tags/${escapeHtml(slugTag(tag))}">#${escapeHtml(tag)}</a>`,
    )
    .join("\n")

  return `${indentation}<article class="featured-card${item.thumbnail ? " has-thumbnail" : ""}">
${thumbnail}${indentation}  <div class="featured-card-body">
${indentation}    <time datetime="${item.updated}">更新于 ${displayDate(item.updated)}</time>
${indentation}    <h3><a href="${escapeHtml(item.href)}">${escapeHtml(item.title)}</a></h3>
${indentation}    <p>${escapeHtml(item.summary)}</p>
${indentation}    <div class="featured-card-footer">
${indentation}      <div class="featured-card-tags">
${tags}
${indentation}      </div>
${indentation}      <a class="featured-card-read" href="${escapeHtml(item.href)}" aria-label="阅读《${escapeHtml(item.title)}》">阅读全文 <span aria-hidden="true">→</span></a>
${indentation}    </div>
${indentation}  </div>
${indentation}</article>`
}

function renderFeaturedCards(items: FeaturedArticle[], indentation = "      "): string {
  return items.map((item) => renderFeaturedCard(item, indentation)).join("\n")
}

function renderSectionHeading(options: {
  description: string
  id: string
  image?: string
  imageAlt?: string
  title: string
}): string {
  const visual =
    options.image === undefined
      ? ""
      : `
      <img class="home-section-visual" src="${escapeHtml(options.image)}" alt="${escapeHtml(options.imageAlt ?? "")}" loading="lazy">`

  return `    <div class="home-section-heading${options.image ? " has-visual" : ""}">
      <div class="home-section-copy">
        <h2 id="${escapeHtml(options.id)}">${escapeHtml(options.title)}</h2>
        <p>${escapeHtml(options.description)}</p>
      </div>${visual}
    </div>`
}

function renderHeroPreview(homepage: HomepageConfiguration, heroImageUrl?: string): string {
  if (heroImageUrl !== undefined) {
    return `<img class="home-preview-image" src="${escapeHtml(heroImageUrl)}" alt="${escapeHtml(homepage.hero.imageAlt ?? "")}" fetchpriority="high">`
  }

  return `<div class="home-preview-window">
        <span class="home-preview-kicker">${escapeHtml(homepage.hero.previewKicker ?? "")}</span>
        <strong class="home-preview-title">${escapeHtml(homepage.hero.previewTitle ?? "")}</strong>
        <div class="home-preview-lines" aria-hidden="true">
          <i></i><i></i><i></i><i></i>
        </div>
      </div>`
}

export function renderHomepage(homepage: HomepageConfiguration, heroImageUrl?: string): string {
  const frontmatter = stringify({
    title: homepage.metaTitle,
    description: homepage.metaDescription,
  })
  const secondaryAction = homepage.hero.secondaryAction
    ? `\n        <a class="home-button" href="${escapeHtml(homepage.hero.secondaryAction.href)}">${escapeHtml(homepage.hero.secondaryAction.label)}</a>`
    : ""
  const topics = homepage.topics.items
    .map(
      (item) => `      <a class="home-topic-card" href="${escapeHtml(item.href)}">
        <span>${escapeHtml(item.kicker)}</span>
        <strong>${escapeHtml(item.title)}</strong>
        <small>${escapeHtml(item.description)}</small>
      </a>`,
    )
    .join("\n")
  const featured = renderFeaturedCards(homepage.featured.items.slice(0, homepage.featured.limit))
  const footerNote = homepage.footerNote
    ? `
  <aside class="home-note">
    ${escapeHtml(homepage.footerNote)}
  </aside>
`
    : ""

  return `---
${frontmatter}---

<!-- Generated from the configured Obsidian homepage document. Do not edit this file directly. -->

<div class="home-shell">
  <section class="home-hero" aria-labelledby="home-title">
    <div>
      <p class="home-badge">${escapeHtml(homepage.hero.badge)}</p>
      <h1 id="home-title">${escapeHtml(homepage.hero.title)}</h1>
      <p class="home-lead">${escapeHtml(homepage.hero.description)}</p>
      <div class="home-actions">
        <a class="home-button is-primary" href="${escapeHtml(homepage.hero.primaryAction.href)}">${escapeHtml(homepage.hero.primaryAction.label)} <span aria-hidden="true">→</span></a>${secondaryAction}
      </div>
    </div>
    <div class="home-preview" aria-label="${escapeHtml(homepage.hero.imageAlt ?? "知识库阅读预览")}">
      ${renderHeroPreview(homepage, heroImageUrl)}
    </div>
  </section>

  <section class="home-section is-topics" aria-labelledby="topics-title">
${renderSectionHeading({
  id: "topics-title",
  title: homepage.topics.title,
  description: homepage.topics.description,
})}
    <div class="home-topic-grid">
${topics}
    </div>
  </section>

  <section class="home-section is-featured" aria-labelledby="reading-title">
${renderSectionHeading({
  id: "reading-title",
  title: homepage.featured.title,
  description: homepage.featured.description,
  image: homepage.featured.image,
  imageAlt: homepage.featured.imageAlt,
})}
    <div class="featured-card-list is-home">
${featured}
    </div>
    <div class="home-section-footer">
      <a class="home-more-link" href="${escapeHtml(homepage.featured.moreAction.href)}">${escapeHtml(homepage.featured.moreAction.label)} <span aria-hidden="true">→</span></a>
    </div>
  </section>
${footerNote}
</div>
`
}

export function renderFeaturedArchive(homepage: HomepageConfiguration): string {
  const frontmatter = stringify({
    title: "精选文章",
    description: homepage.featured.description,
    unlisted: true,
  })
  const featured = renderFeaturedCards(homepage.featured.items, "  ")
  const visual =
    homepage.featured.image === undefined
      ? ""
      : `
<img class="featured-archive-visual" src="${escapeHtml(homepage.featured.image)}" alt="${escapeHtml(homepage.featured.imageAlt ?? "")}">`

  return `---
${frontmatter}---

<!-- Generated from the configured Obsidian homepage document. Do not edit this file directly. -->
${visual}

<div class="featured-archive-intro">
  <p>${escapeHtml(homepage.featured.description)}</p>
  <span>${homepage.featured.items.length} 篇文章</span>
</div>

<div class="featured-card-list is-archive">
${featured}
</div>
`
}
